---
openapi: 3.0.1
info:
  title: Invoices API
  description: API for managing invoices with authentication and all documented functionalities.
  version: v1
  contact:
    name: MV
    url: https://valenzuela.dev
paths:
  "/invoices":
    get:
      summary: list invoices
      tags:
      - Invoices
      description: JWT token is missing or invalid.
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Invoice"
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    post:
      summary: create invoice
      tags:
      - Invoices
      description: JWT token is missing or invalid.
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Invoice"
        '400':
          description: bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                created_at:
                  type: string
                  format: date
                payment_due:
                  type: string
                  format: date
                description:
                  type: string
                payment_terms:
                  type: integer
                client_name:
                  type: string
                client_email:
                  type: string
                status:
                  type: string
                  enum:
                  - draft
                  - pending
                  - paid
                total:
                  type: number
                sender_address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    postCode:
                      type: string
                    country:
                      type: string
                client_address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    postCode:
                      type: string
                    country:
                      type: string
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      quantity:
                        type: integer
                      price:
                        type: number
                      total:
                        type: number
              required:
              - created_at
              - payment_due
              - description
              - payment_terms
              - client_name
              - client_email
              - status
              - total
              - sender_address
              - client_address
              - items
  "/invoices/{id}":
    parameters:
    - name: id
      in: path
      description: Invoice ID
      required: true
      schema:
        type: string
    get:
      summary: show invoice
      tags:
      - Invoices
      description: JWT token is missing or invalid.
      security:
      - bearerAuth: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Invoice"
        '404':
          description: not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      summary: update invoice
      tags:
      - Invoices
      description: JWT token is missing or invalid.
      security:
      - bearerAuth: []
      parameters: []
      responses:
        '200':
          description: updated
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Invoice"
        '404':
          description: not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                payment_terms:
                  type: integer
                client_name:
                  type: string
                client_email:
                  type: string
                status:
                  type: string
                  enum:
                  - draft
                  - pending
                  - paid
                total:
                  type: number
                sender_address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    postCode:
                      type: string
                    country:
                      type: string
                client_address:
                  type: object
                  properties:
                    street:
                      type: string
                    city:
                      type: string
                    postCode:
                      type: string
                    country:
                      type: string
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      quantity:
                        type: integer
                      price:
                        type: number
                      total:
                        type: number
    delete:
      summary: delete invoice
      tags:
      - Invoices
      description: JWT token is missing or invalid.
      security:
      - bearerAuth: []
      responses:
        '204':
          description: no content
        '404':
          description: not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/signup":
    post:
      summary: user signup
      tags:
      - Users
      description: Validation errors, such as email already taken or invalid data.
      parameters: []
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
              required:
              - email
              - password
  "/login":
    post:
      summary: user login
      tags:
      - Users
      description: Invalid email or password.
      parameters: []
      responses:
        '200':
          description: successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  message:
                    type: string
        '401':
          description: unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
              required:
              - email
              - password
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Invoice:
      type: object
      properties:
        id:
          type: string
        created_at:
          type: string
          format: date
        payment_due:
          type: string
          format: date
        description:
          type: string
        payment_terms:
          type: integer
        client_name:
          type: string
        client_email:
          type: string
        status:
          type: string
        total:
          type: number
        sender_address:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            postCode:
              type: string
            country:
              type: string
        client_address:
          type: object
          properties:
            street:
              type: string
            city:
              type: string
            postCode:
              type: string
            country:
              type: string
        items:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              quantity:
                type: integer
              price:
                type: number
              total:
                type: number
security:
- bearerAuth: []
